### ISSUE TITLE
Possibly Change Project Name + Lack of Content

### ISSUE THREAD

**Issue by drew-bozarth** [jasonbohlinger/cpsc354RCCar#3]
I really liked the idea of controlling an RC car with Blockly blocks, however, I can't really tell if this is able to do so. I understand I don't have an RC car to test with, but the code being generated is to move around the turtle in TKinter so it just feels like the Project title is disconnected from the code. I also kind of felt like there was just a lack of content. There were only really 2 different blocks (the loop block is kind of a constant across projects) and I think the RC Car movement is a good idea so there are lots of possible blocks to make. Some ideas could be: "Moving Reverse", "Stop", the ability to control the speed of the car when it is moving forward/backward, "pause for ___ seconds", some way to have the car turning in place, etc.

**Comment by jasonbohlinger** [comment]
We added some information to [README.md](https://github.com/jasonbohlinger/cpsc354RCCar/blob/main/README.md) to better explain how our usage of the Arduino RC car works. Since this, we have added 'stop' (9bbfb77), 'speed' (9c22457), and 'pause' (e4b7351). Thank you for your suggestion on moving backwards, we will keep this issue open until that feature is implemented.

**Comment by jasonbohlinger** [comment]
Commit 91c5976 added 'move_backward' block
